/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import consts.Operations;
import dialogs.DlgIzmeniPredmet;
import dialogs.DlgIzmeniStudenta;
import dialogs.DlgIzmeniZaposlenog;
import domain.Katedra;
import domain.Predmet;
import domain.Student;
import domain.Zaposleni;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import logic.ClientController;
import servercommunication.Communication;
import tranfer.Request;
import tranfer.Response;


/**
 *
 * @author Bosko
 */
public class FrmAdministrator extends javax.swing.JFrame {
    int brojac=0;
    /**
     * Creates new form FrmAdministrator
     */
    public FrmAdministrator() {
        initComponents();
        srediCB();
        ClientController.getInstance().setFa(this);
        pnlPredmet.setVisible(false);
        pnlStudent.setVisible(false);
        pnlZaposljeni.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdmin = new javax.swing.JPanel();
        pnlStudent = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbStudent = new javax.swing.JComboBox();
        btnIzmeniStudenta = new javax.swing.JButton();
        btnObrisiStudent = new javax.swing.JButton();
        pnlPredmet = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbPredmet = new javax.swing.JComboBox();
        btnIzmeniPredmet = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbKatedra = new javax.swing.JComboBox();
        btnObrisiPredmet = new javax.swing.JButton();
        pnlZaposljeni = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbZaposleni = new javax.swing.JComboBox();
        btnIzmeniZaposljenog = new javax.swing.JButton();
        btnObrisiZaposleni = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Izaberi studenta:");

        cbStudent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnIzmeniStudenta.setText("Izmeni");
        btnIzmeniStudenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniStudentaActionPerformed(evt);
            }
        });

        btnObrisiStudent.setText("Obrisi");
        btnObrisiStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStudentLayout = new javax.swing.GroupLayout(pnlStudent);
        pnlStudent.setLayout(pnlStudentLayout);
        pnlStudentLayout.setHorizontalGroup(
            pnlStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(pnlStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnObrisiStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIzmeniStudenta, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlStudentLayout.setVerticalGroup(
            pnlStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnIzmeniStudenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnObrisiStudent)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel3.setText("Izaberi predmet:");

        cbPredmet.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnIzmeniPredmet.setText("Izmeni");
        btnIzmeniPredmet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniPredmetActionPerformed(evt);
            }
        });

        jLabel4.setText("Izaberi katedru:");

        cbKatedra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbKatedra.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbKatedraItemStateChanged(evt);
            }
        });

        btnObrisiPredmet.setText("Obrisi");
        btnObrisiPredmet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiPredmetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPredmetLayout = new javax.swing.GroupLayout(pnlPredmet);
        pnlPredmet.setLayout(pnlPredmetLayout);
        pnlPredmetLayout.setHorizontalGroup(
            pnlPredmetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPredmetLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnlPredmetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPredmetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbKatedra, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPredmet, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pnlPredmetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIzmeniPredmet, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(btnObrisiPredmet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlPredmetLayout.setVerticalGroup(
            pnlPredmetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPredmetLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlPredmetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbKatedra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIzmeniPredmet))
                .addGap(17, 17, 17)
                .addGroup(pnlPredmetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPredmet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnObrisiPredmet)
                    .addComponent(jLabel3))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel5.setText("Izaberi zaposlenog:");

        cbZaposleni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnIzmeniZaposljenog.setText("Izmeni");
        btnIzmeniZaposljenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniZaposljenogActionPerformed(evt);
            }
        });

        btnObrisiZaposleni.setText("Obrisi");
        btnObrisiZaposleni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiZaposleniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlZaposljeniLayout = new javax.swing.GroupLayout(pnlZaposljeni);
        pnlZaposljeni.setLayout(pnlZaposljeniLayout);
        pnlZaposljeniLayout.setHorizontalGroup(
            pnlZaposljeniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlZaposljeniLayout.createSequentialGroup()
                .addGroup(pnlZaposljeniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlZaposljeniLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIzmeniZaposljenog, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlZaposljeniLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnObrisiZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlZaposljeniLayout.setVerticalGroup(
            pnlZaposljeniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlZaposljeniLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlZaposljeniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIzmeniZaposljenog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnObrisiZaposleni)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPredmet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlStudent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlZaposljeni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlAdminLayout.setVerticalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlZaposljeni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPredmet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jMenu1.setText("Dodaj");

        jMenuItem1.setText("Zaposleni");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Student");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Predmet");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Izmeni");

        jMenuItem4.setText("Zaposleni");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Student");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Predmet");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Odjava");

        jMenuItem7.setText("Odjavi se");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        DlgDodajZaposlenog ddz=new DlgDodajZaposlenog(this, rootPaneCheckingEnabled);
        ddz.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        DlgDodajStudenta dds=new DlgDodajStudenta(this, rootPaneCheckingEnabled);
        dds.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        DlgDodajPredmet ddp=new DlgDodajPredmet(this, rootPaneCheckingEnabled);
        ddp.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        pnlPredmet.setVisible(false);
        pnlStudent.setVisible(false);
        pnlZaposljeni.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        pnlPredmet.setVisible(false);
        pnlStudent.setVisible(true);
        pnlZaposljeni.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        pnlPredmet.setVisible(true);
        pnlStudent.setVisible(false);
        pnlZaposljeni.setVisible(false);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void cbKatedraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbKatedraItemStateChanged
        unosPredmeta();
    }//GEN-LAST:event_cbKatedraItemStateChanged

    private void btnIzmeniStudentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniStudentaActionPerformed
        ClientController.getInstance().setIzmeniStudent((Student) cbStudent.getSelectedItem());
        DlgIzmeniStudenta dis=new DlgIzmeniStudenta(this, rootPaneCheckingEnabled);
        dis.setVisible(true);
    }//GEN-LAST:event_btnIzmeniStudentaActionPerformed

    private void btnIzmeniPredmetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniPredmetActionPerformed
        ClientController.getInstance().setIzmeniPredmet((Predmet) cbPredmet.getSelectedItem());
        DlgIzmeniPredmet dip=new DlgIzmeniPredmet(this, rootPaneCheckingEnabled);
        dip.setVisible(true);
    }//GEN-LAST:event_btnIzmeniPredmetActionPerformed

    private void btnIzmeniZaposljenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniZaposljenogActionPerformed
        ClientController.getInstance().setIzmeniZaposleni((Zaposleni) cbZaposleni.getSelectedItem());
        DlgIzmeniZaposlenog dzz=new DlgIzmeniZaposlenog(this, rootPaneCheckingEnabled);
        dzz.setVisible(true);
    }//GEN-LAST:event_btnIzmeniZaposljenogActionPerformed

    private void btnObrisiZaposleniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiZaposleniActionPerformed
        Request req=new Request();
        req.setParametar(cbZaposleni.getSelectedItem());
        req.setOperation(Operations.OBRISIZAPOSLENOG);
        Communication.getInstance().sendRequest(req);
    }//GEN-LAST:event_btnObrisiZaposleniActionPerformed

    private void btnObrisiStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStudentActionPerformed
        Request req=new Request();
        req.setParametar(cbStudent.getSelectedItem());
        req.setOperation(Operations.OBRISISTUDENTA);
        Communication.getInstance().sendRequest(req);
    }//GEN-LAST:event_btnObrisiStudentActionPerformed

    private void btnObrisiPredmetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiPredmetActionPerformed
        Request req=new Request();
        req.setParametar(cbPredmet.getSelectedItem());
        req.setOperation(Operations.OBRISIPREDMET);
        Communication.getInstance().sendRequest(req);
    }//GEN-LAST:event_btnObrisiPredmetActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        Request req=new Request();
        req.setOperation(Operations.ODJAVISE);
        req.setZaposleni(ClientController.getInstance().getPrijavljeniZaposleni());
        Communication.getInstance().sendRequest(req);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdministrator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniPredmet;
    private javax.swing.JButton btnIzmeniStudenta;
    private javax.swing.JButton btnIzmeniZaposljenog;
    private javax.swing.JButton btnObrisiPredmet;
    private javax.swing.JButton btnObrisiStudent;
    private javax.swing.JButton btnObrisiZaposleni;
    private javax.swing.JComboBox cbKatedra;
    private javax.swing.JComboBox cbPredmet;
    private javax.swing.JComboBox cbStudent;
    private javax.swing.JComboBox cbZaposleni;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlPredmet;
    private javax.swing.JPanel pnlStudent;
    private javax.swing.JPanel pnlZaposljeni;
    // End of variables declaration//GEN-END:variables

    public void srediCB() {
        cbZaposleni.removeAllItems();
        cbStudent.removeAllItems();
        cbPredmet.removeAllItems();
        cbKatedra.removeAllItems();
        Request req=new Request();
        req.setOperation(Operations.VRATIZAPOSLJENESTUDENTEKATEDRE);
        Communication.getInstance().sendRequest(req);
    }

    public void srediSveCB(Response res) {
        for(Zaposleni z:res.getListaZaposlenih()){
            cbZaposleni.addItem(z);
        }
        for(Student s:res.getListaStudenata()){
            cbStudent.addItem(s);
        }
        ArrayList<Katedra> listaK=(ArrayList<Katedra>) res.getParametar();
        ClientController.getInstance().setListaKatedra(listaK);
        for(Katedra k:listaK){
            cbKatedra.addItem(k);
        }
    }

    public void unosPredmeta(){
        Katedra katedra=(Katedra) cbKatedra.getSelectedItem();
        if(katedra!=null){
            Request req=new Request();
            req.setParametar(katedra);
            req.setOperation(Operations.VRATIPREDMETEKATEDRE);
            Communication.getInstance().sendRequest(req);
        }
    }
    
    public void unesiPredmete(ArrayList<Predmet> parametar) {
        cbPredmet.removeAllItems();
        for(Predmet p:parametar){
            cbPredmet.addItem(p);
        }
    }

    public void obrisano(boolean uspesno) {
        if(uspesno){
            JOptionPane.showMessageDialog(this, "Uspesno!");
            srediCB();
            unosPredmeta();
        }else{
            JOptionPane.showMessageDialog(this, "Greska!");
        }
    }

    public void odjaviSe() {
        ClientController.getInstance().setFa(null);
        ClientController.getInstance().setPrijavljeniZaposleni(null);
        ClientController.getInstance().getFl().setVisible(true);
        this.dispose();
    }
    
    
}
