/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import consts.Operations;
import domain.Polaganje;
import domain.Termin;
import static forms.FrmStudent.student;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import logic.ClientController;
import models.ModelRok;
import servercommunication.Communication;
import tranfer.Request;

/**
 *
 * @author Bosko
 */
public class FrmRok extends javax.swing.JDialog {
SimpleDateFormat sdf=new SimpleDateFormat("dd.MM.yyyy.");
    /**
     * Creates new form FrmRok
     */
    public FrmRok(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ClientController.getInstance().setFr(this);
        lblNazivRoka.setHorizontalAlignment(SwingConstants.CENTER);
        lblDatumi.setHorizontalAlignment(SwingConstants.CENTER);
        lblNazivRoka.setText(ClientController.getInstance().getIzabraniRok().getNaziv()+" rok");
        lblDatumi.setText(sdf.format(ClientController.getInstance().getIzabraniRok().getPocetak())+" - "+sdf.format(ClientController.getInstance().getIzabraniRok().getZavrsetak()));
        srediTabelu();
        if(ClientController.getInstance().getFs()==null){
            btnPrijavi.setVisible(false);
        }
        //namestiBtn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNazivRoka = new javax.swing.JLabel();
        lblDatumi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRok = new javax.swing.JTable();
        btnPrijavi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNazivRoka.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNazivRoka.setText("jLabel1");

        lblDatumi.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblDatumi.setText("jLabel1");

        tblRok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRok);

        btnPrijavi.setText("Prijavi ispit");
        btnPrijavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrijaviActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNazivRoka, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addComponent(lblDatumi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(132, 132, 132))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrijavi, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblNazivRoka)
                .addGap(18, 18, 18)
                .addComponent(lblDatumi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPrijavi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrijaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrijaviActionPerformed
        int i=tblRok.getSelectedRow();
        if(i==-1){
            JOptionPane.showMessageDialog(rootPane, "Izaberite termin");
        }else{
            ModelRok mr=(ModelRok) tblRok.getModel();
            Termin t=mr.getListaT().get(i);
            Request req=new Request();
            Polaganje p=new Polaganje(ClientController.getInstance().getPrijavljeniStudent(), t, 0, 0);
            req.setParametar(p);
            req.setOperation(Operations.PRIJAVIPOLAGANJE);
            Communication.getInstance().sendRequest(req);
        }
    }//GEN-LAST:event_btnPrijaviActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmRok dialog = new FrmRok(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrijavi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDatumi;
    private javax.swing.JLabel lblNazivRoka;
    private javax.swing.JTable tblRok;
    // End of variables declaration//GEN-END:variables

    private void srediTabelu() {
        ModelRok mr=new ModelRok();
        tblRok.setModel(mr);
        Request req= new Request();
        req.setOperation(Operations.VRATIODGOVARAJUCETERMINE);
        req.setParametar(ClientController.getInstance().getIzabraniRok());
        Communication.getInstance().sendRequest(req);
    }

    public void postaviTabeluTermina(Object parametar) {
        ArrayList<Termin> listaT=(ArrayList<Termin>) parametar;
        ModelRok mr=(ModelRok) tblRok.getModel();
        mr.setListaT(listaT);
    }

    private void namestiBtn() {
        Date datum=new Date();
        long d=(ClientController.getInstance().getIzabraniRok().getPocetak().getTime()-datum.getTime())/86400000;
        if(d>5&&d<10){
            btnPrijavi.setEnabled(true);
        }else{
            btnPrijavi.setEnabled(false);
        }
    }

    public void prijaviPolaganje(boolean uspesno) {
        if(uspesno){
            JOptionPane.showMessageDialog(rootPane, "Uspesna prijava");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Neuspesna prijava");
        }
    }
}
