/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import consts.Operations;
import domain.Polaganje;
import domain.Predmet;
import domain.Rok;
import domain.Termin;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logic.ClientController;
import models.ModelPolaganjaZaposleni;
import servercommunication.Communication;
import tranfer.Request;

/**
 *
 * @author Bosko
 */

public class FrmZaposleni extends javax.swing.JFrame {
    private static FrmLogin fl;
    /**
     * Creates new form FrmZaposleni
     */
    public FrmZaposleni() {
        initComponents();
        //fl=aThis;
        ClientController.getInstance().setFz(this);
        lblIme.setText(ClientController.getInstance().getPrijavljeniZaposleni().getIme()+" "+ClientController.getInstance().getPrijavljeniZaposleni().getPrezime());
        ucitajTabelu();
        popuniCB();
        srediCB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPolaganja = new javax.swing.JTable();
        lblIme = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbPredmet = new javax.swing.JComboBox();
        btnPretrazi = new javax.swing.JButton();
        btnOdjaviSe = new javax.swing.JButton();
        btnRok = new javax.swing.JButton();
        cbRok = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tblPolaganja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPolaganja);

        lblIme.setText("jLabel1");

        jButton1.setText("Zapamti ocene");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Izaberi predmet:");

        cbPredmet.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnPretrazi.setText("Pretrazi termine za predmet");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        btnOdjaviSe.setText("Odjavi se");
        btnOdjaviSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjaviSeActionPerformed(evt);
            }
        });

        btnRok.setText("Pogledaj rok");
        btnRok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRokActionPerformed(evt);
            }
        });

        cbRok.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("Dodaj termin za izabrani predmet");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Rok:");

        jLabel3.setText("Datum:");

        txtDatum.setText("dd.MM.yyyy. hh:mm");
        txtDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIme, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOdjaviSe, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(95, 95, 95)
                                                .addComponent(cbRok, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cbPredmet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))))
                                        .addGap(36, 36, 36)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnRok, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 204, Short.MAX_VALUE))
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbRok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRok)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbPredmet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(btnPretrazi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIme)
                            .addComponent(btnOdjaviSe)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ModelPolaganjaZaposleni mpz=(ModelPolaganjaZaposleni) tblPolaganja.getModel();
        ArrayList<Polaganje> listaP=mpz.getLista();
        boolean b=true;
        for(Polaganje pol:listaP){
            if(!(pol.getOcena()==0||(pol.getOcena()>=5&&pol.getOcena()<=10))){
                b=false;
            }
        }
        if(b){
            Request req=new Request();
            req.setParametar(listaP);
            req.setOperation(Operations.UNESIOCENE);
            Communication.getInstance().sendRequest(req);
        }else{
            JOptionPane.showMessageDialog(this, "Pogresan unos ocena");
            srediTabelu();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        srediTabelu();
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnOdjaviSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjaviSeActionPerformed
        Request req=new Request();
        req.setOperation(Operations.ODJAVISE);
        req.setZaposleni(ClientController.getInstance().getPrijavljeniZaposleni());
        Communication.getInstance().sendRequest(req);
    }//GEN-LAST:event_btnOdjaviSeActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
//        Request req=new Request();
//        req.setOperation(Operations.ODJAVISE);
//        req.setZaposleni(ClientController.getInstance().getPrijavljeniZaposleni());
//        Communication.getInstance().sendRequest(req);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
//        Request req=new Request();
//        req.setOperation(Operations.ODJAVISE);
//        req.setZaposleni(ClientController.getInstance().getPrijavljeniZaposleni());
//        Communication.getInstance().sendRequest(req);
          //ClientController.getInstance().getFl().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnRokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRokActionPerformed
        Rok r=(Rok) cbRok.getSelectedItem();
        ClientController.getInstance().setIzabraniRok(r);
        FrmRok fr=new FrmRok(this, rootPaneCheckingEnabled);
        fr.setVisible(true);
    }//GEN-LAST:event_btnRokActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SimpleDateFormat sdf=new SimpleDateFormat("dd.MM.yyyy. hh:mm");
        try {
            Date datum=sdf.parse(txtDatum.getText());
            Rok rok=(Rok) cbRok.getSelectedItem();
            Predmet predmet=(Predmet) cbPredmet.getSelectedItem();
            if(datum.after(rok.getPocetak())&&datum.before(rok.getZavrsetak())){
                Termin termin=new Termin(-1, predmet, rok, datum);
                Request req=new Request();
                req.setParametar(termin);
                req.setOperation(Operations.DODAJTERMIN);
                Communication.getInstance().sendRequest(req);
            }else{
                JOptionPane.showMessageDialog(this, "Datum nije u navedenom roku");
            }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Pogresan format datuma(dd.MM.yyyy. hh:mm)");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmZaposleni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmZaposleni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmZaposleni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmZaposleni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmZaposleni().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdjaviSe;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnRok;
    private javax.swing.JComboBox cbPredmet;
    private javax.swing.JComboBox cbRok;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIme;
    private javax.swing.JTable tblPolaganja;
    private javax.swing.JTextField txtDatum;
    // End of variables declaration//GEN-END:variables

    private void ucitajTabelu() {
        ModelPolaganjaZaposleni mn1=new ModelPolaganjaZaposleni();
        tblPolaganja.setModel(mn1);
    }
    
    private void srediTabelu() {
        Request req= new Request();
        req.setOperation(Operations.VRATIODGOVARAJUCAPOLAGANJA);
        req.setZaposleni(ClientController.getInstance().getPrijavljeniZaposleni());
        req.setParametar(cbPredmet.getSelectedItem());
        Communication.getInstance().sendRequest(req);
    }

    public void postaviTabelePolaganja(ArrayList<Polaganje> listaPolaganja) {
        ModelPolaganjaZaposleni mn=(ModelPolaganjaZaposleni) tblPolaganja.getModel();
        ArrayList<Polaganje> pomocna=new ArrayList<>();
        for(Polaganje po:listaPolaganja){
            if(po.getTermin().getDatum().before(new Date())){
                pomocna.add(po);
            }
        }
        mn.postaviListu(pomocna);
    }

    public void uneteOcene(boolean uspesno) {
        if(!uspesno){
            JOptionPane.showMessageDialog(this, "Neuspesan unos");
        }else{
            JOptionPane.showMessageDialog(this, "Uspesno!");
        }
        srediTabelu();
    }

    private void popuniCB() {
        cbPredmet.removeAllItems();
        Request req =new Request();
        req.setOperation(Operations.VRATIPREDMETEKATEDRE);
        req.setParametar(ClientController.getInstance().getPrijavljeniZaposleni().getKatedra());
        Communication.getInstance().sendRequest(req);
    }

    public void unesiCB(ArrayList<Predmet> parametar) {
        for(Predmet p:parametar){
            cbPredmet.addItem(p);
        }
    }

    public void odjaviSe() {
        ClientController.getInstance().setFz(null);
        ClientController.getInstance().setPrijavljeniZaposleni(null);
        ClientController.getInstance().getFl().setVisible(true);
        this.dispose();
    }
    
    private void srediCB() {
        cbRok.removeAllItems();
        Request req=new Request();
        req.setOperation(Operations.VRATIOVOGODISNJEROKOVE);
        req.setZaposleni(ClientController.getInstance().getPrijavljeniZaposleni());
        Communication.getInstance().sendRequest(req);
    }

    public void postaviCBRokova(ArrayList<Rok> listaRokova) {
        for(Rok r:listaRokova){
            cbRok.addItem(r);
        }
    }
    
}
